fail_fast: true
exclude: "(^vendor/|\\.patch$)"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: "data/"
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: "data/"
      - id: check-merge-conflict
      - id: fix-byte-order-marker

  - repo: local
    hooks:
      - id: update-contributors-txt
        name: Update CONTRIBUTORS.txt
        language: python
        entry: python3 etc/scripts/update_contributors_txt.py
        pass_filenames: false
